=== ziadsalem15/Stendhal-Game/data/conf/achievements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="achievements" type="Q1:achievementsGroup"></element>

	<complexType name="achievementsGroup">
		<sequence>
			<element name="achievement" type="Q1:achievementType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="implementation" type="Q1:implementation"></element>
			<element name="attributes" type="Q1:attributes"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>

	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="identifier" type="Q1:attribute" minOccurs="0"/>
			<element name="title" type="Q1:attribute" minOccurs="0"/>
			<element name="description" type="Q1:attribute" minOccurs="0"/>
			<element name="score" type="Q1:attribute" minOccurs="0"/>
			<element name="active" type="Q1:attribute" minOccurs="0"/>
			<element name="condition" type="Q1:attribute" minOccurs="0"/>
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
	</complexType>

</schema>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/production.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="gourmet">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.class.food"/>
			<title value="Gourmet"/>
			<description value="Order all food types available from Faiumoni's cooks"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new AndCondition(
						new PlayerProducedNumberOfItemsCondition(1, foods),
						new QuestStateStartsWithCondition('coal_for_haunchy','waiting;'))"/>
		</attributes>
	</achievement>
	
	<achievement name="thirsty worker">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.class.drink"/>
			<title value="Thirsty Worker"/>
			<description value="Order all drink types available from Faiumoni's cooks"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new AndCondition(
						new PlayerProducedNumberOfItemsCondition(1, drinks),
						new QuestCompletedCondition('soup_maker'),
						new QuestCompletedCondition('fishsoup_maker'),
						new QuestCompletedCondition('koboldish_torcibud'))"/>
		</attributes>
	</achievement>
	
	<achievement name="alchemist">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.class.resource"/>
			<title value="Alchemist"/>
			<description value="Produce 5 of each kind of precious metal and resource"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new PlayerProducedNumberOfItemsCondition(5, resources)"/>
		</attributes>
	</achievement>

	<achievement name="jenny's assistant">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.flour.1000"/>
			<title value="Jenny's Assistant"/>
			<description value="Produce 1000 flour"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new PlayerProducedNumberOfItemsCondition(1000, 'flour')"/>
		</attributes>
	</achievement>
	
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/semos_monster_quest.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="Semos' Protector">
	  	<type class="achievements" subclass="quest_semos_monster" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.SemosMonsterQuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.daily.0010"/>
			<title value="Semos' Protector"/>
			<description value="Finish daily monster quest 10 times"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('daily', 2, 9)"/>
		</attributes>
	</achievement>
	
	<achievement name="Semos' Guardian">
	  	<type class="achievements" subclass="quest_semos_monster" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.SemosMonsterQuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.daily.0050"/>
			<title value="Semos' Guardian"/>
			<description value="Finish daily monster quest 50 times"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('daily', 2, 49)"/>
		</attributes>
	</achievement>
	
	<achievement name="Semos' Hero">
	  	<type class="achievements" subclass="quest_semos_monster" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.SemosMonsterQuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.daily.0100"/>
			<title value="Semos' Hero"/>
			<description value="Finish daily monster quest 100 times"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('daily', 2, 99)"/>
		</attributes>
	</achievement>
	
	<achievement name="Semos' Champion">
	  	<type class="achievements" subclass="quest_semos_monster" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.SemosMonsterQuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.daily.0250"/>
			<title value="Semos' Champion"/>
			<description value="Finish daily monster quest 250 times"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('daily', 2, 249)"/>
		</attributes>
	</achievement>
	
	<achievement name="Semos' Vanquisher">
	  	<type class="achievements" subclass="quest_semos_monster" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.SemosMonsterQuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.daily.0500"/>
			<title value="Semos' Vanquisher"/>
			<description value="Finish daily monster quest 500 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('daily', 2, 499)"/>
		</attributes>
	</achievement>
	
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/item.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="pocket_money">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.money.100" />
			<title value = "First pocket money" />
			<description value = "Loot 100 money from creatures" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(100, 'money')" />
		</attributes>
	</achievement>
	
		
	<achievement name="rich">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.money.1000000" />
			<title value = "You don't need it anymore" />
			<description value = "Loot 1000000 money from creatures" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1000000, 'money')" />
		</attributes>
	</achievement>
	
		
	<achievement name="red">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.red" />
			<title value = "Amazon's Menace" />
			<description value = "Loot a complete red equipment set" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'red armor', 'red helmet', 'red cloak', 'red legs', 'red boots', 'red shield')" />
		</attributes>
	</achievement>
		
	<achievement name="blue">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.blue" />
			<title value = "Feeling Blue" />
			<description value = "Loot a complete blue equipment set" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'blue armor', 'blue helmet', 'blue striped cloak', 'blue legs', 'blue boots', 'blue shield')" />
		</attributes>
	</achievement>
		
	<achievement name="elvish">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.elvish" />
			<title value = "Nalwor's Bane" />
			<description value = "Loot a complete elvish equipment set" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'elvish armor', 'elvish helmet', 'elvish cloak', 'elvish legs', 'elvish boots', 'elvish shield')" />
		</attributes>
	</achievement>
		
	<achievement name="shadow">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.shadow" />
			<title value = "Shadow Dweller" />
			<description value = "Loot a complete shadow equipment set" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'shadow armor', 'shadow helmet', 'shadow cloak', 'shadow legs', 'shadow boots', 'shadow shield')" />
		</attributes>
	</achievement>
		
	<achievement name="chaos">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.chaos" />
			<title value = "Chaotic Looter" />
			<description value = "Loot a complete chaos equipment set" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'chaos armor', 'chaos helmet', 'chaos cloak', 'chaos legs', 'chaos boots', 'chaos shield')" />
		</attributes>
	</achievement>
	
		
	<achievement name="golden">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.golden" />
			<title value = "Golden Boy" />
			<description value = "Loot a complete golden equipment set" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'golden armor', 'golden helmet', 'golden cloak', 'golden legs', 'golden boots', 'golden shield')" />
		</attributes>
	</achievement>
	
		
	<achievement name="black">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.black" />
			<title value = "Come to the dark side" />
			<description value = "Loot a complete black equipment set" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'black armor', 'black helmet', 'black cloak', 'black legs', 'black boots', 'black shield')" />
		</attributes>
	</achievement>
		
	<achievement name="mainio">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.mainio" />
			<title value = "Excellent Stuff" />
			<description value = "Loot a complete mainio equipment set" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'mainio armor', 'mainio helmet', 'mainio cloak', 'mainio legs', 'mainio boots', 'mainio shield')" />
		</attributes>
	</achievement>

		
	<achievement name="xeno">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.set.xeno" />
			<title value = "A Bit Xenophobic?" />
			<description value = "Loot a complete xeno equipment set" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'xeno armor', 'xeno helmet', 'xeno cloak', 'xeno legs', 'xeno boots', 'xeno shield')" />
		</attributes>
	</achievement>
	
	<achievement name="dragon">
		<type class="achievements" subclass="item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ItemAchievementFactory"/>
		<attributes>
			<identifier value = "item.cloak.dragon" />
			<title value = "Dragon Slayer" />
			<description value = "Loot all dragon cloaks" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerLootedNumberOfItemsCondition(1, 'black dragon cloak', 'blue dragon cloak', 'bone dragon cloak')" />
		</attributes>
	</achievement>
	
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/ados_item_quest.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="supporter">
		<type class="achievements" subclass="quest_ados_items" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "quest.special.daily_item.0010" />
			<title value = "Ados' Supporter" />
			<description value = "Finish daily item quest 10 times" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new QuestStateGreaterThanCondition('daily_item', 2, 9)" />
		</attributes>
	</achievement>
	
	<achievement name="provider">
		<type class="achievements" subclass="quest_ados_items" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "quest.special.daily_item.0050" />
			<title value = "Ados' Provider" />
			<description value = "Finish daily item quest 50 times" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new QuestStateGreaterThanCondition('daily_item', 2, 49)" />
		</attributes>
	</achievement>
	
	<achievement name="supplier">
		<type class="achievements" subclass="quest_ados_items" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "quest.special.daily_item.0100" />
			<title value = "Ados' Supplier" />
			<description value = "Finish daily item quest 100 times" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new QuestStateGreaterThanCondition('daily_item', 2, 99)" />
		</attributes>
	</achievement>

	<achievement name="stockpiler">
		<type class="achievements" subclass="quest_ados_items" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "quest.special.daily_item.0250" />
			<title value = "Ados' Stockpiler" />
			<description value = "Finish daily item quest 250 times" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new QuestStateGreaterThanCondition('daily_item', 2, 249)" />
		</attributes>
	</achievement>

	<achievement name="hoarder">
		<type class="achievements" subclass="quest_ados_items" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "quest.special.daily_item.0500" />
			<title value = "Ados' Hoarder" />
			<description value = "Finish daily item quest 500 times" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new QuestStateGreaterThanCondition('daily_item', 2, 499)" />
		</attributes>
	</achievement>
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/friend.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="children">
		<type class="achievements" subclass="friend" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FriendAchievementFactory"/>
		<attributes>
			<identifier value = "friend.quests.children" />
			<title value = "Childrens' friend" />
			<description value = "Complete quests for all children" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new AndCondition(
						new QuestStartedCondition('susi'),
						new QuestCompletedCondition('introduce_players'),
						new QuestCompletedCondition('plinks_toy'),
						new QuestCompletedCondition('toys_collector'),
						new AndCondition(new QuestActiveCondition('campfire'), new QuestNotInStateCondition('campfire', 'start')),
						new QuestStateStartsWithCondition('icecream_for_annie','eating;'),
						new QuestStateStartsWithCondition('chocolate_for_elisabeth','eating;'),
						new QuestCompletedCondition('find_jefs_mom'),
						new AndCondition(new QuestActiveCondition('fishsoup_for_hughie'), new QuestNotInStateCondition('fishsoup_for_hughie', 'start'),
						new QuestCompletedCondition('coded_message')))))" />
		</attributes>
	</achievement>
	
	<achievement name="find">
		<type class="achievements" subclass="friend" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FriendAchievementFactory"/>
		<attributes>
			<identifier value = "friend.quests.find" />
			<title value = "Private Detective" />
			<description value = "Find all lost and hidden people" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new AndCondition(
						new QuestCompletedCondition('find_rat_kids'),
						new QuestCompletedCondition('find_ghosts'),
						new ChatCondition() {
							@Override
							public boolean fire(final Player player, final Sentence sentence, final Entity entity) {
								if (!player.hasQuest('seven_cherubs')) {
									return false;
								}
								final String npcDoneText = player.getQuest('seven_cherubs');
								final String[] done = npcDoneText.split(';');
								final int left = 7 - done.length;
								return left < 0;
							}
						})" />
		</attributes>
	</achievement>
	
	<achievement name="karma">
		<type class="achievements" subclass="friend" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FriendAchievementFactory"/>
		<attributes>
			<identifier value = "friend.karma.250" />
			<title value = "Good Samaritan" />
			<description value = "Earn a very good karma" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new ChatCondition() {
				@Override
				public boolean fire(final Player player, final Sentence sentence, final Entity entity) {
					return player.getKarma()>250;
				}
			}" />
		</attributes>
	</achievement>
	
		<achievement name="seasonal">
		<type class="achievements" subclass="friend" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FriendAchievementFactory"/>
		<attributes>
			<identifier value = "friend.meet.seasonal" />
			<title value = "Still Believing" />
			<description value = "Meet Santa Claus and Easter Bunny" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new AndCondition(new QuestWithPrefixCompletedCondition('meet_santa_'), new QuestWithPrefixCompletedCondition('meet_bunny_'))" />
		</attributes>
	</achievement>
</achievements>

=== ziadsalem15/Stendhal-Game/tests/games/stendhal/server/core/config/testmithrilbourgh_enemy_army.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="Sergeanttest">
	  	<type class="achievements" subclass="quest_mithrilbourgh_enemy_army" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.MithrilbourghEnemyArmyAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.kill_enemy_army.0005"/>
			<title value="Sergeant"/>
			<description value="Finish Kill Enemy Army quest 5 times"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('kill_enemy_army', IDX, 4)"/>
		</attributes>
	</achievement>

	<achievement name="Majortest">
	  	<type class="achievements" subclass="quest_mithrilbourgh_enemy_army" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.MithrilbourghEnemyArmyAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.kill_enemy_army.0025"/>
			<title value="Major"/>
			<description value="Finish Kill Enemy Army quest 25 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('kill_enemy_army', IDX, 24)"/>
		</attributes>
	</achievement>
	
	<achievement name="Field Marshaltest">
	  	<type class="achievements" subclass="quest_mithrilbourgh_enemy_army" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.MithrilbourghEnemyArmyAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.kill_enemy_army.0100"/>
			<title value="Major General"/>
			<description value="Finish Kill Enemy Army quest 100 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('kill_enemy_army', IDX, 99)"/>
		</attributes>
	</achievement>
	

</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/kirdneh_item.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="Archaeologist">
	  	<type class="achievements" subclass="quest_kirdneh_item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.KirdnehItemAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.weekly_item.0005"/>
			<title value="Archaeologist"/>
			<description value="Finish weekly item quest 5 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('weekly_item', 2, 4)"/>
		</attributes>
	</achievement>
	
	<achievement name="Dedicated Archaeologist">
	  	<type class="achievements" subclass="quest_kirdneh_item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.KirdnehItemAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.weekly_item.0025"/>
			<title value="Dedicated Archaeologist"/>
			<description value="Finish weekly item quest 25 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('weekly_item', 2, 24)"/>
		</attributes>
	</achievement>
	
	<achievement name="Senior Archaeologist">
	  	<type class="achievements" subclass="quest_kirdneh_item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.KirdnehItemAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.weekly_item.0050"/>
			<title value="Senior Archaeologist"/>
			<description value="Finish weekly item quest 50 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('weekly_item', 2, 49"/>
		</attributes>
	</achievement>

	<achievement name="Master Archaeologist">
	  	<type class="achievements" subclass="quest_kirdneh_item" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.KirdnehItemAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.weekly_item.0100"/>
			<title value="Master Archaeologist"/>
			<description value="Finish weekly item quest 100 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('weekly_item', 2, 99"/>
		</attributes>
	</achievement>
</achievements>

=== ziadsalem15/Stendhal-Game/tests/games/stendhal/server/core/config/testproduction.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="gourmettest">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.class.food"/>
			<title value="Gourmet"/>
			<description value="Order all food types available from Faiumoni's cooks"/>
			<score value="Achievement.MEDIUM_BASE_SCORE"/>
			<active value="true"/>
			<condition value="new AndCondition(
						new PlayerProducedNumberOfItemsCondition(1, foods),
						new QuestStateStartsWithCondition('coal_for_haunchy','waiting;'))"/>
		</attributes>
	</achievement>
	
	<achievement name="thirsty workertest">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.class.drink"/>
			<title value="Thirsty Worker"/>
			<description value="Order all drink types available from Faiumoni's cooks"/>
			<score value="Achievement.MEDIUM_BASE_SCORE"/>
			<active value="true"/>
			<condition value="new AndCondition(
						new PlayerProducedNumberOfItemsCondition(1, drinks),
						new QuestCompletedCondition('soup_maker'),
						new QuestCompletedCondition('fishsoup_maker'),
						new QuestCompletedCondition('koboldish_torcibud'))"/>
		</attributes>
	</achievement>
	
	<achievement name="alchemisttest">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.class.resource"/>
			<title value="Alchemist"/>
			<description value="Produce 5 of each kind of precious metal and resource"/>
			<score value="Achievement.HARD_BASE_SCORE"/>
			<active value="true"/>
			<condition value="new PlayerProducedNumberOfItemsCondition(5, resources)"/>
		</attributes>
	</achievement>

	<achievement name="jenny's assistanttest">
	  	<type class="achievements" subclass="production" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.ProductionAchievementFactory"/>
		<attributes>
			<identifier value="production.flour.1000"/>
			<title value="Jenny's Assistant"/>
			<description value="Produce 1000 flour"/>
			<score value="Achievement.EASY_BASE_SCORE"/>
			<active value="true"/>
			<condition value="new PlayerProducedNumberOfItemsCondition(1000, 'flour')"/>
		</attributes>
	</achievement>
	
</achievements>
