=== ziadsalem15/Stendhal-Game/data/conf/achievements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="achievements" type="Q1:achievementsGroup"></element>

	<complexType name="achievementsGroup">
		<sequence>
			<element name="achievement" type="Q1:achievementType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="implementation" type="Q1:implementation"></element>
			<element name="attributes" type="Q1:attributes"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>

	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="identifier" type="Q1:attribute" minOccurs="0"/>
			<element name="title" type="Q1:attribute" minOccurs="0"/>
			<element name="description" type="Q1:attribute" minOccurs="0"/>
			<element name="score" type="Q1:attribute" minOccurs="0"/>
			<element name="active" type="Q1:attribute" minOccurs="0"/>
			<element name="condition" type="Q1:attribute" minOccurs="0"/>
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
	</complexType>

</schema>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/interior_zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="semos">
		<type class="achievements" subclass="interior_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.InteriorZoneAchievementFactory"/>
		<attributes>
			<identifier value = "zone.interior.semos" />
			<title value = "Home maker" />
			<description value = "Visit all interior zones in the Semos region" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerVisitedZonesInRegionCondition('semos', Boolean.FALSE, Boolean.FALSE)" />
		</attributes>
	</achievement>
	
	<achievement name="nalwor">
		<type class="achievements" subclass="interior_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.InteriorZoneAchievementFactory"/>
		<attributes>
			<identifier value = "zone.interior.nalwor" />
			<title value = "Elf visitor" />
			<description value = "Visit all interior zones in the Nalwor region" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerVisitedZonesInRegionCondition('nalwor', Boolean.FALSE, Boolean.FALSE)" />
		</attributes>
	</achievement>
	
	<achievement name="ados">
		<type class="achievements" subclass="interior_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.InteriorZoneAchievementFactory"/>
		<attributes>
			<identifier value = "zone.interior.ados" />
			<title value = "Up town guy" />
			<description value = "Visit all accessible interior zones in the Ados region" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerVisitedZonesInRegionCondition('ados', Boolean.FALSE, Boolean.FALSE)" />
		</attributes>
	</achievement>

	<achievement name="wofol">
		<type class="achievements" subclass="interior_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.InteriorZoneAchievementFactory"/>
		<attributes>
			<identifier value = "zone.interior.wofolcity" />
			<title value = "Kobold City" />
			<description value = "Visit all interior zones in Wo'lof" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerVisitedZonesInRegionCondition('wofol city', Boolean.FALSE, Boolean.FALSE)" />
		</attributes>
	</achievement>

	<achievement name="magic">
		<type class="achievements" subclass="interior_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.InteriorZoneAchievementFactory"/>
		<attributes>
			<identifier value = "zone.interior.magiccity" />
			<title value = "Magic City" />
			<description value = "Visit all interior zones in the underground Magic city" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerVisitedZonesInRegionCondition('magic city', Boolean.FALSE, Boolean.FALSE)" />
		</attributes>
	</achievement>
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/experience.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="level10">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ExperienceAchievementFactory"/>
		<attributes>
			<identifier value = "xp.level.010" />
			<title value = "Greenhorn" />
			<description value = "Reach level 10" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new LevelGreaterThanCondition(9)" />
		</attributes>
	</achievement>
	
	<achievement name="level50">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ExperienceAchievementFactory"/>
		<attributes>
			<identifier value = "xp.level.050" />
			<title value = "Novice" />
			<description value = "Reach level 50" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new LevelGreaterThanCondition(49)" />
		</attributes>
	</achievement>
	
	<achievement name="level100">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ExperienceAchievementFactory"/>
		<attributes>
			<identifier value = "xp.level.100" />
			<title value = "Apprentice" />
			<description value = "Reach level 100" />
			<score value = 1 />
			<active value = true />
			<condition value = new LevelGreaterThanCondition(99) />
		</attributes>
	</achievement>

	<achievement name="level200">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "xp.level.200" />
			<title value = "Adventurer" />
			<description value = "Reach level 200" />
			<score value = 2 />
			<active value = true />
			<condition value = new LevelGreaterThanCondition(199) />
		</attributes>
	</achievement>

	<achievement name="level300">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "xp.level.300" />
			<title value = "Experienced Adventurer" />
			<description value = "Reach level 300" />
			<score value = 2 />
			<active value = true />
			<condition value = new LevelGreaterThanCondition(299) />
		</attributes>
	</achievement>
	
	<achievement name="level400">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.AdosItemQuestAchievementsFactory"/>
		<attributes>
			<identifier value = "xp.level.400" />
			<title value = "Master Adventurer" />
			<description value = "Reach level 400" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new LevelGreaterThanCondition(399)" />
		</attributes>
	</achievement>
	
	<achievement name="level500">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ExperienceAchievementFactory"/>
		<attributes>
			<identifier value = "xp.level.500" />
			<title value = "Stendhal Master" />
			<description value = "Reach level 500" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new LevelGreaterThanCondition(499)" />
		</attributes>
	</achievement>
	
	<achievement name="level597">
		<type class="achievements" subclass="experience" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ExperienceAchievementFactory"/>
		<attributes>
			<identifier value = "xp.level.597" />
			<title value = "Stendhal High Master" />
			<description value = "Reach level 597" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new LevelGreaterThanCondition(596)" />
		</attributes>
	</achievement>
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/fighting.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="rats">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.rats" />
			<title value = "Rat Hunter" />
			<description value = "Kill 15 rats" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition('rat', 15)" />
		</attributes>
	</achievement>
	
	<achievement name="exterminator">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.exterminator" />
			<title value = "Exterminator" />
			<description value = "Kill 10 rats of each kind" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition(10, 'rat', 'caverat', 'razorrat', 'venomrat', 'zombie rat', 'giantrat', 'ratman', 'ratwoman', 'archrat')" />
		</attributes>
	</achievement>
	
	<achievement name="deer">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.deer" />
			<title value = "Deer Hunter" />
			<description value = "Kill 25 deer" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition('deer', 25)" />
		</attributes>
	</achievement>
	
	<achievement name="boar">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.boars" />
			<title value = "Boar Hunter" />
			<description value = "Kill 20 boar" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition('boar', 20)" />
		</attributes>
	</achievement>
	
	<achievement name="bears">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.bears" />
			<title value = "Bear Hunter" />
			<description value = "Kill 10 black bears, 10 bears and 10 babybears" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition(10, 'bear', 'black bear', 'babybear')" />
		</attributes>
	</achievement>
	
	<achievement name="foxes">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.foxes" />
			<title value = "Fox Hunter" />
			<description value = "Kill 20 foxes" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition('fox', 20)" />
		</attributes>
	</achievement>
	
	
	<achievement name="safari">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.safari" />
			<title value = "Boar Hunter" />
			<description value = "Kill 30 tigers, 30 lions and 50 elephants" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new AndCondition(new PlayerHasKilledNumberOfCreaturesCondition('tiger', 30),
												 new PlayerHasKilledNumberOfCreaturesCondition('lion', 30),
												 new PlayerHasKilledNumberOfCreaturesCondition('elephant', 50))" />
		</attributes>
	</achievement>
	
	<achievement name="ents">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.general.ents" />
			<title value = "Wood Cutter" />
			<description value = "Kill 10 ents, 10 entwifes and 10 old ents" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerHasKilledNumberOfCreaturesCondition(10, 'ent', 'entwife', 'old ent')" />
		</attributes>
	</achievement>
	
	<achievement name="rare">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.special.rare" />
			<title value = "Poacher" />
			<description value = "Kill any rare creature" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new KilledRareCreatureCondition()" />
		</attributes>
	</achievement>
	
	<achievement name="solo">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.special.all" />
			<title value = "Legend" />
			<description value = "Kill all creatures solo" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new KilledSoloAllCreaturesCondition()" />
		</attributes>
	</achievement>
	
	<achievement name="team">
		<type class="achievements" subclass="fighting" tileid="-1"/>
		<implementation class-name="games.stendhal.server.FightingAchievementFactory"/>
		<attributes>
			<identifier value = "fight.special.allshared" />
			<title value = "Team Player" />
			<description value = "Kill all creatures in a team" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new KilledSharedAllCreaturesCondition()" />
		</attributes>
	</achievement>
	
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/obtain.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="wish">
		<type class="achievements" subclass="obtain" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ObtainAchievementsFactory"/>
		<attributes>
			<identifier value = "obtain.wish" />
			<title value = "A wish came true" />
			<description value = "Get an item from the wishing well" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerGotNumberOfItemsFromWellCondition(0)" />
		</attributes>
	</achievement>
	
	<achievement name="vegetable">
		<type class="achievements" subclass="obtain" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ObtainAchievementsFactory"/>
		<attributes>
			<identifier value = "obtain.harvest.vegetable" />
			<title value = "Farmer" />
			<description value = "Harvest 3 of all vegetables that grow in Faiumoni" />
			<score value = "1" />
			<active value = "true" />
			<condition value = "new PlayerHasHarvestedNumberOfItemsCondition(3, 'carrot', 'salad', 'broccoli', 'cauliflower', 'leek',
						'onion', 'courgette', 'spinach', 'collard', 'garlic', 'artichoke')" />
		</attributes>
	</achievement>

	<achievement name="fishing">
		<type class="achievements" subclass="obtain" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ObtainAchievementsFactory"/>
		<attributes>
			<identifier value = "obtain.fish" />
			<title value = "Fisherman" />
			<description value = "Catch 15 of each type of fish" />
			<score value = "2" />
			<active value = "true" />
			<condition value = "new PlayerHasHarvestedNumberOfItemsCondition(15, 'char', 'clownfish', 'cod', 'mackerel', 'perch',
						'red lionfish', 'roach', 'surgeonfish', 'trout')" />
		</attributes>
	</achievement>
	
	<achievement name="quest">
		<type class="achievements" subclass="obtain" tileid="-1"/>
		<implementation class-name="games.stendhal.server.ObtainAchievementsFactory"/>
		<attributes>
			<identifier value = "quest.special.collector" />
			<title value = "Ultimate Collector" />
			<description value = "Finish ultimate collector quest" />
			<score value = "5" />
			<active value = "true" />
			<condition value = "new QuestCompletedCondition('ultimate_collector')" />
		</attributes>
	</achievement>
	
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/underground_zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="Canary">
	  	<type class="achievements" subclass="underground_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.UndergroundZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.underground.semos"/>
			<title value="Canary"/>
			<description value="Visit all underground zones in the Semos region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('semos', Boolean.TRUE, Boolean.FALSE)"/>
		</attributes>
	</achievement>
	
	<achievement name="Fear not drows nor hell">
	  	<type class="achievements" subclass="underground_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.UndergroundZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.underground.nalwor"/>
			<title value="Fear not drows nor hell"/>
			<description value="Visit all underground zones in the Nalwor region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('nalwor', Boolean.TRUE, Boolean.FALSE)"/>
		</attributes>
	</achievement>

	<achievement name="Labyrinth Solver">
	  	<type class="achievements" subclass="underground_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.UndergroundZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.underground.athor"/>
			<title value="Labyrinth Solver"/>
			<description value="Visit all underground zones in the Nalwor region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('athor', Boolean.TRUE, Boolean.FALSE)"/>
		</attributes>
	</achievement>
	
	<achievement name="Human Mole">
	  	<type class="achievements" subclass="underground_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.UndergroundZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.underground.amazon"/>
			<title value="Human Mole"/>
			<description value="Visit all underground zones in the Amazon region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('amazon', Boolean.TRUE, Boolean.FALSE)"/>
		</attributes>
	</achievement>

	<achievement name="Human Mole">
	  	<type class="achievements" subclass="underground_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.UndergroundZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.underground.ados"/>
			<title value="Deep Dweller"/>
			<description value="Visit all underground zones in the Ados region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('ados', Boolean.TRUE, Boolean.FALSE)"/>
		</attributes>
	</achievement>	
	
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/quest.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	<achievement name="elf princess">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.elf_princess.0025"/>
			<title value="Faiumoni's Casanova"/>
			<description value="Finish elf princess quest 25 times"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('elf_princess', 2, 24)"/>
		</attributes>
	</achievement>
	
	
	<achievement name="kill monks">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.kill_monks.0025"/>
			<title value="Heretic"/>
			<description value="Finish Kill Monks quest 25 times"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('kill_monks', 2, 24)"/>
		</attributes>
	</achievement>
	
	<achievement name="Maze Pathfinder">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.maze"/>
			<title value="Pathfinder"/>
			<description value="Finish the maze"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('maze', 2, 0)"/>
		</attributes>
	</achievement>
	
	<achievement name="Deathmatch">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.deathmatch"/>
			<title value="Deathmatch Hero"/>
			<description value="Earn 100,000 points in deathmatch"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestStateGreaterThanCondition('deathmatch_score', 0, 100000)"/>
		</attributes>
	</achievement>
	
	<achievement name="Semos City Quests">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.semos"/>
			<title value="Aide to Semos folk"/>
			<description value="Complete all quests in Semos City"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestsInRegionCompletedCondition(Region.SEMOS_CITY)"/>
		</attributes>
	</achievement>
	
	<achievement name="Ados City Quests">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.special.ados"/>
			<title value="Helper of Ados city dwellers"/>
			<description value="Complete all quests in Ados City"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestsInRegionCompletedCondition(Region.ADOS_CITY)"/>
		</attributes>
	</achievement>

	<achievement name="Nearly All Quests">
	  	<type class="achievements" subclass="quest" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.QuestAchievementFactory"/>
		<attributes>
			<identifier value="quest.count.80"/>
			<title value="Quest Junkie"/>
			<description value="Complete at least 80 quests"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new QuestCountCompletedCondition(80)"/>
		</attributes>
	</achievement>
</achievements>

=== ziadsalem15/Stendhal-Game/data/conf/achievements/outside_zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	<achievement name="junior explorer">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.semos" />
			<title value="Junior Explorer" />
			<description value="Visit all outside zones in the Semos region"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('semos', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>

	<achievement name="big city explorer">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.ados" />
			<title value="Big City Explorer"/>
			<description value="Visit all outside zones in the Ados region"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('ados', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>
	
	<achievement name="far south">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.fado" />
			<title value="Far South" />
			<description value="Visit all outside zones in the Fado region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('fado', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>
	
	<achievement name="scout">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.orril" />
			<title value="Scout" />
			<description value="Visit all outside zones in the Orril region"/>
			<score value="2"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('orril', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>
	
	<achievement name="jungle explorer">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.amazon" />
			<title value="Jungle Explorer" />
			<description value="Visit all outside zones in the Amazon region"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('amazon', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>
	
	<achievement name="tourist">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.athor" />
			<title value="Tourist" />
			<description value="Visit all outside zones in the Athor region"/>
			<score value="1"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('athor', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>
	
	<achievement name="sky tower">
	  	<type class="achievements" subclass="outside_zone" tileid="-1"/>
		<implementation class-name="games.stendhal.server.entity.core.rp.achievement.factory.OutsideZoneAchievementFactory"/>
		<attributes>
			<identifier value="zone.outside.kikareukin" />
			<title value="Sky Tower" />
			<description value="Visit all outside zones in the Kikareukin region"/>
			<score value="5"/>
			<active value="true"/>
			<condition value="new PlayerVisitedZonesInRegionCondition('kikareukin', Boolean.TRUE, Boolean.TRUE)"/>
		</attributes>
	</achievement>

</achievements>
